var dominionBaseSets = [
    [
        "First Game [images]",
        "Cellar",
        "Market",
        "Merchant",
        "Militia",
        "Mine",
        "Moat",
        "Remodel",
        "Smithy",
        "Village",
        "Workshop",
        "Landscapes and Additional Cards"
    ],
    [
        "Size Distortion [images]",
        "Artisan",
        "Bandit",
        "Bureaucrat",
        "Chapel",
        "Festival",
        "Gardens",
        "Sentry",
        "Throne Room",
        "Witch",
        "Workshop",
        "Landscapes and Additional Cards"
    ],
    [
        "Deck Top [images]",
        "Artisan",
        "Bureaucrat",
        "Council Room",
        "Festival",
        "Harbinger",
        "Laboratory",
        "Moneylender",
        "Sentry",
        "Vassal",
        "Village",
        "Landscapes and Additional Cards"
    ],
    [
        "Sleight of Hand [images]",
        "Cellar",
        "Council Room",
        "Festival",
        "Gardens",
        "Library",
        "Harbinger",
        "Militia",
        "Poacher",
        "Smithy",
        "Throne Room",
        "Landscapes and Additional Cards"
    ],
    [
        "Improvements [images]",
        "Artisan",
        "Cellar",
        "Market",
        "Merchant",
        "Mine",
        "Moat",
        "Moneylender",
        "Poacher",
        "Remodel",
        "Witch",
        "Landscapes and Additional Cards"
    ],
    [
        "Silver & Gold [images]",
        "Bandit",
        "Bureaucrat",
        "Chapel",
        "Harbinger",
        "Laboratory",
        "Merchant",
        "Mine",
        "Moneylender",
        "Throne Room",
        "Vassal",
        "Landscapes and Additional Cards"
    ],
    [
        "Underlings [images]",
        "Cellar",
        "Festival",
        "Library",
        "Sentry",
        "Vassal",
        "Courtier",
        "Diplomat",
        "Minion",
        "Nobles",
        "Pawn",
        "Landscapes and Additional Cards"
    ],
    [
        "Grand Scheme [images]",
        "Artisan",
        "Council Room",
        "Market",
        "Militia",
        "Workshop",
        "Bridge",
        "Mill",
        "Mining Village",
        "Patrol",
        "Shanty Town",
        "Landscapes and Additional Cards"
    ],
    [
        "Deconstruction [images]",
        "Bandit",
        "Mine",
        "Remodel",
        "Throne Room",
        "Village",
        "Diplomat",
        "Harem",
        "Lurker",
        "Replace",
        "Swindler",
        "Landscapes and Additional Cards"
    ],
    [
        "Reach for Tomorrow [images]",
        "Artisan",
        "Cellar",
        "Council Room",
        "Vassal",
        "Village",
        "Cutpurse",
        "Ghost Ship",
        "Lookout",
        "Sea Hag",
        "Treasure Map",
        "Landscapes and Additional Cards"
    ],
    [
        "Repetition [images]",
        "Festival",
        "Harbinger",
        "Militia",
        "Workshop",
        "Caravan",
        "Explorer",
        "Outpost",
        "Pearl Diver",
        "Pirate Ship",
        "Treasury",
        "Landscapes and Additional Cards"
    ],
    [
        "Give and Take [images]",
        "Library",
        "Market",
        "Moneylender",
        "Witch",
        "Ambassador",
        "Fishing Village",
        "Haven",
        "Island",
        "Salvager",
        "Smugglers",
        "Landscapes and Additional Cards"
    ],
    [
        "Forbidden Arts [images]",
        "Bandit",
        "Cellar",
        "Council Room",
        "Gardens",
        "Laboratory",
        "Throne Room",
        "Apprentice",
        "Familiar",
        "Possession",
        "University",
        "Landscapes and Additional Cards",
        "Potion"
    ],
    [
        "Potion Mixers [images]",
        "Cellar",
        "Festival",
        "Militia",
        "Poacher",
        "Smithy",
        "Alchemist",
        "Apothecary",
        "Golem",
        "Herbalist",
        "Transmute",
        "Landscapes and Additional Cards",
        "Potion"
    ],
    [
        "Chemistry Lesson [images]",
        "Bureaucrat",
        "Market",
        "Moat",
        "Remodel",
        "Vassal",
        "Witch",
        "Alchemist",
        "Golem",
        "Philosopher's Stone",
        "University",
        "Landscapes and Additional Cards",
        "Potion"
    ],
    [
        "Biggest Money [images]",
        "Artisan",
        "Harbinger",
        "Laboratory",
        "Mine",
        "Moneylender",
        "Bank",
        "Grand Market",
        "Mint",
        "Royal Seal",
        "Venture",
        "Landscapes and Additional Cards"
    ],
    [
        "The King's Army [images]",
        "Bureaucrat",
        "Council Room",
        "Merchant",
        "Moat",
        "Village",
        "Expand",
        "Goons",
        "King's Court",
        "Rabble",
        "Vault",
        "Landscapes and Additional Cards"
    ],
    [
        "The Good Life [images]",
        "Artisan",
        "Bureaucrat",
        "Cellar",
        "Gardens",
        "Village",
        "Contraband",
        "Counting House",
        "Hoard",
        "Monument",
        "Mountebank",
        "Landscapes and Additional Cards"
    ],
    [
        "Bounty of the Hunt [images]",
        "Cellar",
        "Festival",
        "Militia",
        "Moneylender",
        "Smithy",
        "Harvest",
        "Horn of Plenty",
        "Hunting Party",
        "Menagerie",
        "Tournament",
        "Landscapes and Additional Cards"
    ],
    [
        "Bad Omens [images]",
        "Bureaucrat",
        "Laboratory",
        "Merchant",
        "Poacher",
        "Throne Room",
        "Fortune Teller",
        "Hamlet",
        "Horn of Plenty",
        "Jester",
        "Remake",
        "Landscapes and Additional Cards"
    ],
    [
        "The Jester's Workshop [images]",
        "Artisan",
        "Laboratory",
        "Market",
        "Remodel",
        "Workshop",
        "Fairgrounds",
        "Farming Village",
        "Horse Traders",
        "Jester",
        "Young Witch",
        "Landscapes and Additional Cards",
        "Bane pile:Merchant"
    ],
    [
        "Highway Robbery [images]",
        "Cellar",
        "Library",
        "Moneylender",
        "Throne Room",
        "Workshop",
        "Highway",
        "Inn",
        "Margrave",
        "Noble Brigand",
        "Oasis",
        "Landscapes and Additional Cards"
    ],
    [
        "Adventures Abroad [images]",
        "Festival",
        "Laboratory",
        "Remodel",
        "Sentry",
        "Vassal",
        "Crossroads",
        "Farmland",
        "Fool's Gold",
        "Oracle",
        "Spice Merchant",
        "Landscapes and Additional Cards"
    ],
    [
        "High and Low [images]",
        "Cellar",
        "Moneylender",
        "Throne Room",
        "Witch",
        "Workshop",
        "Hermit",
        "Hunting Grounds",
        "Mystic",
        "Poor House",
        "Wandering Minstrel",
        "Landscapes and Additional Cards"
    ],
    [
        "Chivalry and Revelry [images]",
        "Festival",
        "Gardens",
        "Laboratory",
        "Library",
        "Remodel",
        "Altar",
        "Knights",
        "Rats",
        "Scavenger",
        "Squire",
        "Landscapes and Additional Cards"
    ],
    [
        "Arts and Crafts [images]",
        "Laboratory",
        "Cellar",
        "Workshop",
        "Festival",
        "Moneylender",
        "Stonemason",
        "Advisor",
        "Baker",
        "Journeyman",
        "Merchant Guild",
        "Landscapes and Additional Cards"
    ],
    [
        "Clean Living [images]",
        "Bandit",
        "Militia",
        "Moneylender",
        "Gardens",
        "Village",
        "Butcher",
        "Baker",
        "Candlestick Maker",
        "Doctor",
        "Soothsayer",
        "Landscapes and Additional Cards"
    ],
    [
        "Gilding the Lily [images]",
        "Library",
        "Merchant",
        "Remodel",
        "Market",
        "Sentry",
        "Plaza",
        "Masterpiece",
        "Candlestick Maker",
        "Taxman",
        "Herald",
        "Landscapes and Additional Cards"
    ],
    [
        "Level Up [images]",
        "Market",
        "Merchant",
        "Militia",
        "Throne Room",
        "Workshop",
        "Dungeon",
        "Gear",
        "Guide",
        "Lost City",
        "Miser",
        "Landscapes and Additional Cards",
        "Training"
    ],
    [
        "Son of Size Distortion [images]",
        "Bandit",
        "Bureaucrat",
        "Gardens",
        "Moneylender",
        "Witch",
        "Amulet",
        "Duplicate",
        "Giant",
        "Messenger",
        "Treasure Trove",
        "Landscapes and Additional Cards",
        "Bonfire",
        "Raid"
    ],
    [
        "Everything in Moderation [images]",
        "Cellar",
        "Library",
        "Remodel",
        "Village",
        "Workshop",
        "Enchantress",
        "Forum",
        "Legionary",
        "Overlord",
        "Temple",
        "Landscapes and Additional Cards",
        "Windfall",
        "Orchard"
    ],
    [
        "Silver Bullets [images]",
        "Bureaucrat",
        "Gardens",
        "Laboratory",
        "Market",
        "Moneylender",
        "Catapult",
        "Charm",
        "Farmers' Market",
        "Groundskeeper",
        "Patrician",
        "Landscapes and Additional Cards",
        "Conquest",
        "Aqueduct"
    ],
    [
        "Night Shift [images]",
        "Druid",
        "Exorcist",
        "Ghost Town",
        "Idol",
        "Night Watchman",
        "Bandit",
        "Gardens",
        "Mine",
        "Poacher",
        "Smithy",
        "Landscapes and Additional Cards",
        "Boons",
        "Boons for Druid",
        "The Earth's Gift",
        "The Flame's Gift",
        "The Forest's Gift"
    ],
    [
        "Idle Hands [images]",
        "Bard",
        "Conclave",
        "Cursed Village",
        "Devil's Workshop",
        "Tragic Hero",
        "Cellar",
        "Harbinger",
        "Market",
        "Merchant",
        "Moneylender",
        "Landscapes and Additional Cards",
        "Boons",
        "Hexes"
    ],
    [
        "It Takes a Villager [images]",
        "Acting Troupe",
        "Cargo Ship",
        "Recruiter",
        "Seer",
        "Treasurer",
        "Market",
        "Merchant",
        "Mine",
        "Smithy",
        "Vassal",
        "Landscapes and Additional Cards",
        "Road Network"
    ],
    [
        "Capture the Flag [images]",
        "Flag Bearer",
        "Lackeys",
        "Scholar",
        "Swashbuckler",
        "Villain",
        "Cellar",
        "Festival",
        "Harbinger",
        "Remodel",
        "Workshop",
        "Landscapes and Additional Cards",
        "Barracks",
        "Pageant"
    ],
    [
        "Pony Express [images]",
        "Barge",
        "Destrier",
        "Paddock",
        "Stockpile",
        "Supplies",
        "Artisan",
        "Cellar",
        "Market",
        "Mine",
        "Village",
        "Landscapes and Additional Cards",
        "Stampede",
        "Way of the Seal"
    ],
    [
        "Garden of Cats [images]",
        "Black Cat",
        "Displace",
        "Sanctuary",
        "Scrap",
        "Snowy Village",
        "Bandit",
        "Gardens",
        "Harbinger",
        "Merchant",
        "Moat",
        "Landscapes and Additional Cards",
        "Toil",
        "Way of the Mole"
    ]
];