var hinterlandsSets = [
    [
        "Introduction [images]",
        "Cache",
        "Crossroads",
        "Develop",
        "Haggler",
        "Jack of All Trades",
        "Margrave",
        "Nomad Camp",
        "Oasis",
        "Spice Merchant",
        "Stables",
        "Landscapes and Additional Cards"
    ],
    [
        "Fair Trades [images]",
        "Border Village",
        "Cartographer",
        "Develop",
        "Duchess",
        "Farmland",
        "Ill-Gotten Gains",
        "Noble Brigand",
        "Silk Road",
        "Stables",
        "Trader",
        "Landscapes and Additional Cards"
    ],
    [
        "Bargains [images]",
        "Border Village",
        "Cache",
        "Duchess",
        "Fool's Gold",
        "Haggler",
        "Highway",
        "Nomad Camp",
        "Scheme",
        "Spice Merchant",
        "Trader",
        "Landscapes and Additional Cards"
    ],
    [
        "Gambits [images]",
        "Cartographer",
        "Crossroads",
        "Embassy",
        "Inn",
        "Jack of All Trades",
        "Mandarin",
        "Nomad Camp",
        "Oasis",
        "Oracle",
        "Tunnel",
        "Landscapes and Additional Cards"
    ],
    [
        "Highway Robbery [images]",
        "Cellar",
        "Library",
        "Moneylender",
        "Throne Room",
        "Workshop",
        "Highway",
        "Inn",
        "Margrave",
        "Noble Brigand",
        "Oasis",
        "Landscapes and Additional Cards"
    ],
    [
        "Adventures Abroad [images]",
        "Festival",
        "Laboratory",
        "Remodel",
        "Sentry",
        "Vassal",
        "Crossroads",
        "Farmland",
        "Fool's Gold",
        "Oracle",
        "Spice Merchant",
        "Landscapes and Additional Cards"
    ],
    [
        "Money for Nothing [images]",
        "Replace",
        "Patrol",
        "Pawn",
        "Shanty Town",
        "Torturer",
        "Cache",
        "Cartographer",
        "Jack of All Trades",
        "Silk Road",
        "Tunnel",
        "Landscapes and Additional Cards"
    ],
    [
        "The Duke's Ball [images]",
        "Conspirator",
        "Duke",
        "Harem",
        "Masquerade",
        "Upgrade",
        "Duchess",
        "Haggler",
        "Inn",
        "Noble Brigand",
        "Scheme",
        "Landscapes and Additional Cards"
    ],
    [
        "Travelers [images]",
        "Cutpurse",
        "Island",
        "Lookout",
        "Merchant Ship",
        "Warehouse",
        "Cartographer",
        "Crossroads",
        "Farmland",
        "Silk Road",
        "Stables",
        "Landscapes and Additional Cards"
    ],
    [
        "Diplomacy [images]",
        "Ambassador",
        "Bazaar",
        "Caravan",
        "Embargo",
        "Smugglers",
        "Embassy",
        "Farmland",
        "ill-Gotten Gains",
        "Noble Brigand",
        "Trader",
        "Landscapes and Additional Cards"
    ],
    [
        "Schemes and Dreams [images]",
        "Apothecary",
        "Apprentice",
        "Herbalist",
        "Philosopher's Stone",
        "Transmute",
        "Duchess",
        "Fool's Gold",
        "Ill-Gotten Gains",
        "Jack of All Trades",
        "Scheme",
        "Landscapes and Additional Cards",
        "Potion"
    ],
    [
        "Wine Country [images]",
        "Apprentice",
        "Familiar",
        "Golem",
        "University",
        "Vineyard",
        "Crossroads",
        "Farmland",
        "Haggler",
        "Highway",
        "Nomad Camp",
        "Landscapes and Additional Cards",
        "Potion"
    ],
    [
        "Instant Gratification [images]",
        "Bishop",
        "Expand",
        "Hoard",
        "Mint",
        "Watchtower",
        "Farmland",
        "Haggler",
        "Ill-Gotten Gains",
        "Noble Brigand",
        "Trader",
        "Landscapes and Additional Cards"
    ],
    [
        "Treasure Trove [images]",
        "Bank",
        "Monument",
        "Royal Seal",
        "Trade Route",
        "Venture",
        "Cache",
        "Develop",
        "Fool's Gold",
        "Ill-Gotten Gains",
        "Mandarin",
        "Landscapes and Additional Cards"
    ],
    [
        "Blue Harvest [images]",
        "Hamlet",
        "Horn of Plenty",
        "Horse Traders",
        "Jester",
        "Tournament",
        "Fool's Gold",
        "Mandarin",
        "Noble Brigand",
        "Trader",
        "Tunnel",
        "Landscapes and Additional Cards"
    ],
    [
        "Traveling Circus [images]",
        "Fairgrounds",
        "Farming Village",
        "Hunting Party",
        "Jester",
        "Menagerie",
        "Border Village",
        "Embassy",
        "Fool's Gold",
        "Nomad Camp",
        "Oasis",
        "Landscapes and Additional Cards"
    ],
    [
        "Far From Home [images]",
        "Cartographer",
        "Develop",
        "Embassy",
        "Fool's Gold",
        "Haggler",
        "Beggar",
        "Count",
        "Feodum",
        "Marauder",
        "Wandering Minstrel",
        "Landscapes and Additional Cards",
        "Ruins"
    ],
    [
        "Expeditions [images]",
        "Crossroads",
        "Farmland",
        "Highway",
        "Spice Merchant",
        "Tunnel",
        "Altar",
        "Catacombs",
        "Ironmonger",
        "Poor House",
        "Storeroom",
        "Landscapes and Additional Cards"
    ],
    [
        "Exchanges [images]",
        "Butcher",
        "Herald",
        "Masterpiece",
        "Soothsayer",
        "Stonemason",
        "Border Village",
        "Develop",
        "Ill-Gotten Gains",
        "Stables",
        "Trader",
        "Landscapes and Additional Cards"
    ],
    [
        "Road to Riches [images]",
        "Advisor",
        "Baker",
        "Candlestick Maker",
        "Journeyman",
        "Merchant Guild",
        "Crossroads",
        "Farmland",
        "Highway",
        "Spice Merchant",
        "Tunnel",
        "Landscapes and Additional Cards"
    ],
    [
        "Traders and Raiders [images]",
        "Haunted Woods",
        "Lost City",
        "Page",
        "Port",
        "Wine Merchant",
        "Develop",
        "Farmland",
        "Haggler",
        "Spice Merchant",
        "Trader",
        "Landscapes and Additional Cards",
        "Raid"
    ],
    [
        "Journeys [images]",
        "Bridge Troll",
        "Distant Lands",
        "Giant",
        "Guide",
        "Ranger",
        "Cartographer",
        "Crossroads",
        "Highway",
        "Inn",
        "Silk Road",
        "Landscapes and Additional Cards",
        "Expedition",
        "Inheritance"
    ],
    [
        "Simple Plans [images]",
        "Catapult",
        "Forum",
        "Patrician",
        "Temple",
        "Villa",
        "Border Village",
        "Develop",
        "Haggler",
        "Ill-Gotten Gains",
        "Stables",
        "Landscapes and Additional Cards",
        "Donate",
        "Labyrinth"
    ],
    [
        "Expansion [images]",
        "Castles",
        "Charm",
        "Encampment",
        "Engineer",
        "Legionary",
        "Cache",
        "Farmland",
        "Highway",
        "Spice Merchant",
        "Tunnel",
        "Landscapes and Additional Cards",
        "Battlefield",
        "Fountain"
    ],
    [
        "Search Party [images]",
        "Cobbler",
        "Conclave",
        "Druid",
        "Faithful Hound",
        "Werewolf",
        "Cartographer",
        "Highway",
        "Inn",
        "Oasis",
        "Scheme",
        "Landscapes and Additional Cards",
        "Boons",
        "Hexes",
        "Boons for Druid",
        "The Mountain's Gift",
        "The Sky's Gift",
        "The Sun's Gift"
    ],
    [
        "Counting Sheep [images]",
        "Bard",
        "Crypt",
        "Leprechaun",
        "Pooka",
        "Shepherd",
        "Crossroads",
        "Farmland",
        "Haggler",
        "Noble Brigand",
        "Tunnel",
        "Landscapes and Additional Cards",
        "Boons",
        "Hexes"
    ],
    [
        "Sweetened Deals [images]",
        "Flag Bearer",
        "Lackeys",
        "Mountain Village",
        "Silk Merchant",
        "Spices",
        "Cartographer",
        "Develop",
        "Farmland",
        "Haggler",
        "Spice Merchant",
        "Landscapes and Additional Cards",
        "Silos"
    ],
    [
        "A Penny Saved [images]",
        "Ducat",
        "Patron",
        "Scepter",
        "Seer",
        "Swashbuckler",
        "Cache",
        "Crossroads",
        "Noble Brigand",
        "Oasis",
        "Trader",
        "Landscapes and Additional Cards",
        "Barracks",
        "Guildhall"
    ],
    [
        "Big Blue [images]",
        "Black Cat",
        "Falconer",
        "Sheepdog",
        "Sleigh",
        "Village Green",
        "Cartographer",
        "Fool's Gold",
        "Margrave",
        "Trader",
        "Tunnel",
        "Landscapes and Additional Cards",
        "Banish",
        "Way of the Turtle"
    ],
    [
        "Intersection [images]",
        "Cardinal",
        "Hostelry",
        "Livery",
        "Mastermind",
        "Supplies",
        "Develop",
        "Farmland",
        "Haggler",
        "Nomad Camp",
        "Stables",
        "Landscapes and Additional Cards",
        "Gamble",
        "Way of the Mouse"
    ]
];