var renaissanceSets = [
    [
        "Overture [images]",
        "Acting Troupe",
        "Experiment",
        "Flag Bearer",
        "Hideout",
        "Improve",
        "Inventor",
        "Lackeys",
        "Old Witch",
        "Seer",
        "Treasurer",
        "Landscapes and Additional Cards",
        "Fair"
    ],
    [
        "Prelude [images]",
        "Border Guard",
        "Cargo Ship",
        "Ducat",
        "Mountain Village",
        "Priest",
        "Recruiter",
        "Sculptor",
        "Silk Merchant",
        "Swashbuckler",
        "Villain",
        "Landscapes and Additional Cards",
        "Citadel",
        "Star Chart"
    ],
    [
        "It Takes a Villager [images]",
        "Acting Troupe",
        "Cargo Ship",
        "Recruiter",
        "Seer",
        "Treasurer",
        "Market",
        "Merchant",
        "Mine",
        "Smithy",
        "Vassal",
        "Landscapes and Additional Cards",
        "Road Network"
    ],
    [
        "Capture the Flag [images]",
        "Flag Bearer",
        "Lackeys",
        "Scholar",
        "Swashbuckler",
        "Villain",
        "Cellar",
        "Festival",
        "Harbinger",
        "Remodel",
        "Workshop",
        "Landscapes and Additional Cards",
        "Barracks",
        "Pageant"
    ],
    [
        "Memento Mori [images]",
        "Experiment",
        "Flag Bearer",
        "Patron",
        "Recruiter",
        "Silk Merchant",
        "Ironworks",
        "Lurker",
        "Patrol",
        "Swindler",
        "Upgrade",
        "Landscapes and Additional Cards",
        "Citadel"
    ],
    [
        "Clockwork Court [images]",
        "Acting Troupe",
        "Inventor",
        "Research",
        "Scepter",
        "Scholar",
        "Courtier",
        "Mining Village",
        "Nobles",
        "Replace",
        "Steward",
        "Landscapes and Additional Cards",
        "Fleet",
        "Sinister Plot"
    ],
    [
        "Free Shipping [images]",
        "Acting Troupe",
        "Cargo Ship",
        "Lackeys",
        "Research",
        "Spices",
        "Embargo",
        "Island",
        "Outpost",
        "Smugglers",
        "Wharf",
        "Landscapes and Additional Cards",
        "Innovation"
    ],
    [
        "Digging for Treasure [images]",
        "Border Guard",
        "Flag Bearer",
        "Inventor",
        "Sculptor",
        "Swashbuckler",
        "Caravan",
        "Native Village",
        "Salvager",
        "Tactician",
        "Treasure Map",
        "Landscapes and Additional Cards",
        "Crop Rotation",
        "Silos"
    ],
    [
        "Peek-a-boo [images]",
        "Cargo Ship",
        "Improve",
        "Lackeys",
        "Patron",
        "Sculptor",
        "Silk Merchant",
        "Alchemist",
        "Apothecary",
        "Golem",
        "Scrying Pool",
        "Landscapes and Additional Cards",
        "Potion",
        "Cathedral"
    ],
    [
        "Dreamers of Dreams [images]",
        "Cargo Ship",
        "Old Witch",
        "Priest",
        "Scepter",
        "Scholar",
        "Expand",
        "Monument",
        "Vault",
        "Watchtower",
        "Worker's Village",
        "Landscapes and Additional Cards",
        "Academy"
    ],
    [
        "Movers and Shakers [images]",
        "Hideout",
        "Patron",
        "Research",
        "Treasurer",
        "Villain",
        "Bank",
        "City",
        "Grand Market",
        "Loan",
        "Rabble",
        "Landscapes and Additional Cards",
        "Capitalism",
        "Citadel"
    ],
    [
        "Sweetened Deals [images]",
        "Flag Bearer",
        "Lackeys",
        "Mountain Village",
        "Silk Merchant",
        "Spices",
        "Cartographer",
        "Develop",
        "Farmland",
        "Haggler",
        "Spice Merchant",
        "Landscapes and Additional Cards",
        "Silos"
    ],
    [
        "A Penny Saved [images]",
        "Ducat",
        "Patron",
        "Scepter",
        "Seer",
        "Swashbuckler",
        "Cache",
        "Crossroads",
        "Noble Brigand",
        "Oasis",
        "Trader",
        "Landscapes and Additional Cards",
        "Barracks",
        "Guildhall"
    ],
    [
        "Stargazing [images]",
        "Border Guard",
        "Patron",
        "Seer",
        "Silk Merchant",
        "Swashbuckler",
        "Hermit",
        "Mystic",
        "Procession",
        "Sage",
        "Wandering Minstrel",
        "Landscapes and Additional Cards",
        "Star Chart"
    ],
    [
        "Sewer Rats [images]",
        "Flag Bearer",
        "Improve",
        "Lackeys",
        "Mountain Village",
        "Research",
        "Count",
        "Counterfeit",
        "Cultist",
        "Graverobber",
        "Rats",
        "Landscapes and Additional Cards",
        "Ruins",
        "Crop Rotation",
        "Sewers"
    ],
    [
        "Combo Corner [images]",
        "Ducat",
        "Experiment",
        "Hideout",
        "Sculptor",
        "Seer",
        "Herald",
        "Horn of Plenty",
        "Horse Traders",
        "Jester",
        "Stonemason",
        "Landscapes and Additional Cards",
        "Canal"
    ],
    [
        "Filling the Coffers [images]",
        "Priest",
        "Recruiter",
        "Spices",
        "Swashbuckler",
        "Treasurer",
        "Baker",
        "Butcher",
        "Menagerie",
        "Merchant Guild",
        "Plaza",
        "Landscapes and Additional Cards",
        "City Gate",
        "Star Chart"
    ],
    [
        "Progress [images]",
        "Experiment",
        "Improve",
        "Recruiter",
        "Seer",
        "Silk Merchant",
        "Hireling",
        "Ranger",
        "Raze",
        "Swamp Hag",
        "Transmogrify",
        "Landscapes and Additional Cards",
        "Training",
        "Piazza"
    ],
    [
        "Once Upon a Time [images]",
        "Acting Troupe",
        "Lackeys",
        "Priest",
        "Sculptor",
        "Spices",
        "Distant Lands",
        "Duplicate",
        "Haunted Woods",
        "Royal Carriage",
        "Storyteller",
        "Landscapes and Additional Cards",
        "Ferry",
        "Innovation"
    ],
    [
        "Exploring the City [images]",
        "Cargo Ship",
        "Experiment",
        "Mountain Village",
        "Priest",
        "Sculptor",
        "City Quarter",
        "Farmers' Market",
        "Groundskeeper",
        "Sacrifice",
        "Wild Hunt",
        "Landscapes and Additional Cards",
        "Exploration",
        "Battlefield"
    ],
    [
        "Navigating the Sewers [images]",
        "Acting Troupe",
        "Flag Bearer",
        "Improve",
        "Old Witch",
        "Scepter",
        "Chariot Race",
        "Enchantress",
        "Gladiator",
        "Patrician",
        "Villa",
        "Landscapes and Additional Cards",
        "Ritual",
        "Sewers"
    ],
    [
        "Becoming a Monster [images]",
        "Experiment",
        "Mountain Village",
        "Old Witch",
        "Research",
        "Spices",
        "Devil's Workshop",
        "Monastery",
        "Shepherd",
        "Skulk",
        "Tragic Hero",
        "Landscapes and Additional Cards",
        "Hexes",
        "Exploration"
    ],
    [
        "True Believers [images]",
        "Border Guard",
        "Cargo Ship",
        "Scholar",
        "Sculptor",
        "Villain",
        "Blessed Village",
        "Crypt",
        "Faithful Hound",
        "Sacred Grove",
        "Secret Cave",
        "Landscapes and Additional Cards",
        "Boons",
        "Cathedral",
        "Piazza"
    ],
    [
        "Biding Time [images]",
        "Cavalry",
        "Coven",
        "Displace",
        "Fisherman",
        "Goatherd",
        "Ducat",
        "Priest",
        "Recruiter",
        "Scepter",
        "Swashbuckler",
        "Landscapes and Additional Cards",
        "Sinister Plot",
        "Way of the Turtle"
    ],
    [
        "Villager Madness [images]",
        "Cardinal",
        "Groom",
        "Kiln",
        "Livery",
        "Wayfarer",
        "Border Guard",
        "Flag Bearer",
        "Patron",
        "Silk Merchant",
        "Spices",
        "Landscapes and Additional Cards",
        "Demand",
        "Academy"
    ]
];