var seasideSets = [
    [
        "High Seas [images]",
        "Bazaar",
        "Caravan",
        "Embargo",
        "Explorer",
        "Haven",
        "Island",
        "Lookout",
        "Pirate Ship",
        "Smugglers",
        "Wharf",
        "Landscapes and Additional Cards"
    ],
    [
        "Buried Treasure [images]",
        "Ambassador",
        "Cutpurse",
        "Fishing Village",
        "Lighthouse",
        "Outpost",
        "Pearl Diver",
        "Tactician",
        "Treasure Map",
        "Warehouse",
        "Wharf",
        "Landscapes and Additional Cards"
    ],
    [
        "Shipwrecks [images]",
        "Ghost Ship",
        "Merchant Ship",
        "Native Village",
        "Navigator",
        "Pearl Diver",
        "Salvager",
        "Sea Hag",
        "Smugglers",
        "Treasury",
        "Warehouse",
        "Landscapes and Additional Cards"
    ],
    [
        "Reach for Tomorrow [images]",
        "Artisan",
        "Cellar",
        "Council Room",
        "Vassal",
        "Village",
        "Cutpurse",
        "Ghost Ship",
        "Lookout",
        "Sea Hag",
        "Treasure Map",
        "Landscapes and Additional Cards"
    ],
    [
        "Repetition [images]",
        "Festival",
        "Harbinger",
        "Militia",
        "Workshop",
        "Caravan",
        "Explorer",
        "Outpost",
        "Pearl Diver",
        "Pirate Ship",
        "Treasury",
        "Landscapes and Additional Cards"
    ],
    [
        "Give and Take [images]",
        "Library",
        "Market",
        "Moneylender",
        "Witch",
        "Ambassador",
        "Fishing Village",
        "Haven",
        "Island",
        "Salvager",
        "Smugglers",
        "Landscapes and Additional Cards"
    ],
    [
        "A Star to Steer By [images]",
        "Secret Passage",
        "Diplomat",
        "Swindler",
        "Wishing Well",
        "Courtier",
        "Lookout",
        "Treasure Map",
        "Ghost Ship",
        "Haven",
        "Outpost",
        "Landscapes and Additional Cards"
    ],
    [
        "Shore Patrol [images]",
        "Patrol",
        "Replace",
        "Shanty Town",
        "Trading Post",
        "Pawn",
        "Island",
        "Wharf",
        "Cutpurse",
        "Lighthouse",
        "Warehouse",
        "Landscapes and Additional Cards"
    ],
    [
        "Bridge Crossing [images]",
        "Lurker",
        "Nobles",
        "Duke",
        "Conspirator",
        "Bridge",
        "Salvager",
        "Embargo",
        "Smugglers",
        "Native Village",
        "Treasury",
        "Landscapes and Additional Cards"
    ],
    [
        "Forewarned [images]",
        "Cutpurse",
        "Embargo",
        "Ghost Ship",
        "Native Village",
        "Treasure Map",
        "Apothecary",
        "Golem",
        "Possession",
        "Scrying Pool",
        "Transmute",
        "Landscapes and Additional Cards",
        "Potion"
    ],
    [
        "Gummed Up [images]",
        "Ambassador",
        "Haven",
        "Sea Hag",
        "Smugglers",
        "Warehouse",
        "Apprentice",
        "Familiar",
        "Herbalist",
        "Philosopher's Stone",
        "Vineyard",
        "Landscapes and Additional Cards",
        "Potion"
    ],
    [
        "Exploding Kingdom [images]",
        "Bishop",
        "City",
        "Grand Market",
        "King's Court",
        "Quarry",
        "Fishing Village",
        "Lookout",
        "Outpost",
        "Tactician",
        "Wharf",
        "Landscapes and Additional Cards"
    ],
    [
        "Pirate Bay [images]",
        "Expand",
        "Hoard",
        "Mint",
        "Trade Route",
        "Watchtower",
        "Bazaar",
        "Lighthouse",
        "Pirate Ship",
        "Smugglers",
        "Warehouse",
        "Landscapes and Additional Cards"
    ],
    [
        "Collector [images]",
        "Embargo",
        "Fishing Village",
        "Merchant Ship",
        "Navigator",
        "Smugglers",
        "Fairgrounds",
        "Farming Village",
        "Fortune Teller",
        "Harvest",
        "Hunting Party",
        "Landscapes and Additional Cards"
    ],
    [
        "Collider [images]",
        "Lighthouse",
        "Salvager",
        "Treasure Map",
        "Treasury",
        "Warehouse",
        "Menagerie",
        "Horn of Plenty",
        "Horse Traders",
        "Jester",
        "Tournament",
        "Landscapes and Additional Cards"
    ],
    [
        "Travelers [images]",
        "Cutpurse",
        "Island",
        "Lookout",
        "Merchant Ship",
        "Warehouse",
        "Cartographer",
        "Crossroads",
        "Farmland",
        "Silk Road",
        "Stables",
        "Landscapes and Additional Cards"
    ],
    [
        "Diplomacy [images]",
        "Ambassador",
        "Bazaar",
        "Caravan",
        "Embargo",
        "Smugglers",
        "Embassy",
        "Farmland",
        "Ill-Gotten Gains",
        "Noble Brigand",
        "Trader",
        "Landscapes and Additional Cards"
    ],
    [
        "Watery Graves [images]",
        "Count",
        "Graverobber",
        "Hermit",
        "Scavenger",
        "Urchin",
        "Native Village",
        "Pirate Ship",
        "Salvager",
        "Treasure Map",
        "Treasury",
        "Landscapes and Additional Cards"
    ],
    [
        "Treasury Peasants [images]",
        "Death Cart",
        "Feodum",
        "Poor House",
        "Urchin",
        "Vagrant",
        "Fishing Village",
        "Haven",
        "Island",
        "Lookout",
        "Warehouse",
        "Landscapes and Additional Cards",
        "Ruins"
    ],
    [
        "Ghosts & Taxes [images]",
        "Cutpurse",
        "Ghost Ship",
        "Haven",
        "Outpost",
        "Smugglers",
        "Butcher",
        "Candlestick Maker",
        "Herald",
        "Soothsayer",
        "Taxman",
        "Landscapes and Additional Cards"
    ],
    [
        "Island Builder [images]",
        "Island",
        "Native Village",
        "Salvager",
        "Tactician",
        "Treasury",
        "Baker",
        "Doctor",
        "Merchant Guild",
        "Plaza",
        "Stonemason",
        "Landscapes and Additional Cards"
    ],
    [
        "Prince of Orange [images]",
        "Amulet",
        "Dungeon",
        "Haunted Woods",
        "Page",
        "Swamp Hag",
        "Caravan",
        "Fishing Village",
        "Merchant Ship",
        "Tactician",
        "Treasure Map",
        "Landscapes and Additional Cards",
        "Mission"
    ],
    [
        "Gifts and Mathoms [images]",
        "Bridge Troll",
        "Caravan Guard",
        "Hireling",
        "Lost City",
        "Messenger",
        "Ambassador",
        "Embargo",
        "Haven",
        "Salvager",
        "Smugglers",
        "Landscapes and Additional Cards",
        "Expedition",
        "Quest"
    ],
    [
        "Boxed In [images]",
        "Castles",
        "Chariot Race",
        "Encampment",
        "Enchantress",
        "Gladiator",
        "Salvager",
        "Smugglers",
        "Tactician",
        "Warehouse",
        "Wharf",
        "Landscapes and Additional Cards",
        "Tax",
        "Wall"
    ],
    [
        "King of the Sea [images]",
        "Archive",
        "Farmers' Market",
        "Overlord",
        "Temple",
        "Wild Hunt",
        "Explorer",
        "Haven",
        "Native Village",
        "Pirate Ship",
        "Sea Hag",
        "Landscapes and Additional Cards",
        "Delve",
        "Fountain"
    ],
    [
        "The New Black [images]",
        "Cobbler",
        "Den of Sin",
        "Ghost Town",
        "Raider",
        "Secret Cave",
        "Caravan",
        "Haven",
        "Merchant Ship",
        "Outpost",
        "Tactician",
        "Landscapes and Additional Cards"
    ],
    [
        "Forbidden Isle [images]",
        "Blessed Village",
        "Cemetery",
        "Idol",
        "Tracker",
        "Tragic Hero",
        "Fishing Village",
        "Ghost Ship",
        "Lookout",
        "Salvager",
        "Treasure Map",
        "Landscapes and Additional Cards",
        "Boons"
    ],
    [
        "Free Shipping [images]",
        "Acting Troupe",
        "Cargo Ship",
        "Lackeys",
        "Research",
        "Spices",
        "Embargo",
        "Island",
        "Outpost",
        "Smugglers",
        "Wharf",
        "Landscapes and Additional Cards",
        "Innovation"
    ],
    [
        "Digging for Treasure [images]",
        "Border Guard",
        "Flag Bearer",
        "Inventor",
        "Sculptor",
        "Swashbuckler",
        "Caravan",
        "Native Village",
        "Salvager",
        "Tactician",
        "Treasure Map",
        "Landscapes and Additional Cards",
        "Crop Rotation",
        "Silos"
    ],
    [
        "Innsmouth [images]",
        "Animal Fair",
        "Barge",
        "Coven",
        "Fisherman",
        "Sheepdog",
        "Caravan",
        "Explorer",
        "Fishing Village",
        "Haven",
        "Treasure Map",
        "Landscapes and Additional Cards",
        "Invest",
        "Way of the Goat",
        "320px"
    ],
    [
        "Ruritania [images]",
        "Bounty Hunter",
        "Cavalry",
        "Falconer",
        "Sleigh",
        "Village Green",
        "Lookout",
        "Smugglers",
        "Outpost",
        "Tactician",
        "Warehouse",
        "Landscapes and Additional Cards",
        "Alliance",
        "Way of the Monkey",
        "320px"
    ]
];